# Corvorum OS - Prompt del Cuervo
# El cuervo observa. El cuervo recuerda. El cuervo ejecuta.

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:#1a0a2e)\
[corvum](fg:#6b3fa0 bg:#2d1b4e)\
[](fg:#2d1b4e bg:#1a0a2e)\
 $os$username$hostname\
 $directory\
$git_branch$git_status\
$python$node$rust$golang$java$docker_context$kubernetes\
$fill\
$cmd_duration$time
[](fg:#1a0a2e)\
$character\
"""

palette = "corvorum"

[palettes.corvorum]
raven  = "#9b59b6"
void   = "#1a0a2e"
dusk   = "#2d1b4e"
ember  = "#c0392b"
bone   = "#d5c5a1"
mist   = "#7f8c8d"
sigil  = "#8e44ad"
blood  = "#922b21"
silver = "#bdc3c7"
gold   = "#f39c12"

[fill]
symbol = " "

[os]
disabled = false
style    = "bold fg:raven bg:dusk"
format   = "[$symbol]($style)"

[os.symbols]
Linux   = " "
Arch    = " "
Debian  = " "
Ubuntu  = " "
Unknown = " "

[username]
show_always = true
style_user  = "bold fg:bone"
style_root  = "bold fg:ember"
format      = "[$user]($style)"

[hostname]
ssh_only = false
style    = "bold fg:mist"
format   = "[@$hostname]($style) "

[directory]
style             = "bold fg:raven"
truncation_length = 4
truncate_to_repo  = true
read_only         = " [RO]"
read_only_style   = "fg:blood"
format            = "[> $path]($style)[$read_only]($read_only_style) "

[git_branch]
style  = "bold fg:sigil"
format = "[git:$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style  = "bold fg:blood"

[cmd_duration]
min_time = 2000
style    = "fg:gold"
format   = "[~$duration]($style) "

[time]
disabled    = false
style       = "fg:mist"
format      = "[$time]($style)"
time_format = "%H:%M"

[python]
style  = "bold fg:gold"
format = "[py $version]($style) "

[node]
style  = "bold fg:raven"
format = "[node $version]($style) "

[rust]
style  = "bold fg:ember"
format = "[rs $version]($style) "

[golang]
style  = "bold fg:silver"
format = "[go $version]($style) "

[docker_context]
style  = "bold fg:mist"
format = "[docker $context]($style) "

[kubernetes]
disabled = false
style    = "bold fg:sigil"
format   = "[k8s $context]($style) "

[character]
success_symbol = "[>](bold fg:raven)"
error_symbol   = "[x](bold fg:blood)"
vimcmd_symbol  = "[o](bold fg:sigil)"