efiSystemPartition: /boot/efi
efiSystemPartitionSize: 300MiB
efiSystemPartitionName: EFI

ensureSuspendToDisk: true
neverCreateSwap: false

drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialSwapChoice: small

swapPartitionName: swap
defaultFileSystemType: ext4
availableFileSystemTypes: [ ext4, btrfs, xfs ]
