defaultGroups:
  - name: sudo
    must_exist: true
    state: true
  - name: audio
    must_exist: false
    state: true
  - name: video
    must_exist: false
    state: true
  - name: plugdev
    must_exist: false
    state: true
  - name: docker
    must_exist: false
    state: true

autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: true
doReusePassword: false
passwordRequirements:
  minLength: 6
  maxLength: -1
userShell: /bin/bash
